#' @title Processing script to grab catchment attributes
#' @author Guy Litt \code{guy.litt@noaa.gov}
#' @description
#' Given catchment location data generated by fs_proc and a user-specified
#' configuration file for datasets and corresponding attributes of interest,
#' acquire the attributes for each catchment, write to parquet database.
#' @details Builds a parquet database for each individual comid when calling
#' \code{proc.attr.hydfab::proc_attr_wrap}. From the directory of comids,
#' creates a sub-directory of a specific dataset.
#'
#' NOTE: In defining the featureSource and featureID, it's expected that the
#' term 'gage_id' is used as a variable in glue syntax to create featureID
#' @seealso [fs_proc] A python package that processes input data for the
#' formulation-selector
#' @usage Rscript fs_attrs_grab.R "/path/to/attribute_config.yaml"

# Changelog / Contributions
#   2024-07-24 Originally created, GL

library(tibble)
library(yaml)
library(ncdf4)
library(proc.attr.hydfab)
library(glue)

# TODO is AWS_NO_SIGN_REQUEST necessary??
# Sys.setenv(AWS_NO_SIGN_REQUEST="YES")

# Define command line argument
cmd_args <- commandArgs("trailingOnly" = TRUE)

if(base::length(cmd_args)!=1){
  warning("Unexpected to have more than one argument in Rscript fs_attrs_grab.R /path/to/attribute_config.yaml.")
}

# Read in config file, e.g.  "~/git/formulation-selector/scripts/eval_ingest/SI/SI_attr_config.yaml"
path_attr_config <- cmd_args[1] # "~/git/formulation-selector/scripts/eval_ingest/xssa/xssa_attr_config.yaml"

Retr_Params <- proc.attr.hydfab::attr_cfig_parse(path_attr_config)

#-----------------------------------------------------
message(glue::glue("Attribute dataset sources include the following:\n
  {paste0(names(Retr_Params$vars),collapse='\n')}"))

message(glue::glue("Attribute variables to be acquired include :
  \n{paste0(unlist(unname(Retr_Params$vars)),collapse='\n')}"))


# PROCESS ATTRIBUTES
dt_comids <- proc.attr.hydfab:::grab_attrs_datasets_fs_wrap(Retr_Params,overwrite = TRUE)

# --------------------------- Compile attributes --------------------------- #
# Demonstration of how to retrieve attributes/comids that exist inside dir_db_attrs:
# The comids of interest
comids <- dt_comids$featureID %>% base::unname() %>% base::unlist()

# The attribute variables of interest
vars <- Retr_Params$vars %>% base::unlist() %>% base::unname()

dat_all_attrs <- proc.attr.hydfab::retrieve_attr_exst(comids, vars,
                                                      Retr_Params$paths$dir_db_attrs)
base::rm(dat_all_attrs)
